module.exports ={

    CONSTANTS:{
        // *** ALGUNOS CODIGOS DE ERROR CON LA BD
        PROTOCOL_CONNECTION_LOST: 'PROTOCOL_CONNECTION_LOST',
        ER_CON_COUNT_ERROR: 'ECONNREFUSED',
        ER_ACCESS_DENIED_ERROR: 'ER_ACCESS_DENIED_ERROR',
        // *** FIN 
    } 
}